# Generated by Django 5.1.3 on 2024-11-19 02:57

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(null=True, upload_to=accounts.models.user_directory_path, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default='这个人很懒，还没有自我介绍~', max_length=500, verbose_name='自我介绍'),
        ),
    ]
