name: werewolves
networks:
  web_network:
    driver: bridge
  db_network:
    driver: bridge

services:
  mysql:
    container_name: mysql
    restart: always
    image: mysql:9.1
    volumes:
      - /home/ubuntu/mysql:/var/lib/mysql # TODO: 更改路径
    env_file:
      - .env
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    expose:
      - 3306
    networks:
      - db_network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.4.1
    container_name: redis
    restart: always
    expose:
      - 6379
    networks:
      - db_network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  app:
    container_name: app
    restart: always
    build: .
    volumes:
      - ./media:/usr/share/nginx/media
    command: >
      bash -c
      "python manage.py makemigrations accounts &&
      python manage.py migrate &&
      DJANGO_SETTINGS_MODULE=app.settings daphne -b 0.0.0.0 -p 8000 app.asgi:application"
    expose:
      - 8000
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - web_network
      - db_network

  celery:
    container_name: celery
    restart: always
    build: .
    command: >
      bash -c
      "celery -A app worker --loglevel=info"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - web_network
      - db_network

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/app.conf:/etc/nginx/nginx.conf:ro
      - ./dist:/usr/share/nginx/html:ro
      - ./media:/usr/share/nginx/media
    depends_on:
      - app
      - celery
    networks:
      - web_network
    ports:
      - "8080:8080"